filum/filum/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('search/', views.search),
    path('profile/', views.profile),
    path('user/', include('user.urls'))
]

filum/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name="registerform"),
    path('profile/', views.profile, name="myprofile")

]

filum/user/models.py
from django.db import models

# Create your models here.

class User (models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    photo_profile = models.ImageField(default='fallback.png', blank=True)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.name}"

filum/user/forms.py
from django import forms
from .models import User

class UserRegisterForm(forms.ModelForm):
    class Meta :
        model = User
        fields = ("name","email","photo_profile","slug")

filum/filum/views.py
from django.shortcuts import render

def home(request) :
    return render(request, 'home.html')

def search(request) :
    return render(request, 'search.html')

def profile(request) :
    return render(request, 'profile.html')

filum/user/views.py
from django.shortcuts import render
from .forms import UserRegisterForm
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request) :
    if request.method == 'POST' :
        form = UserRegisterForm(request.POST)
        if form.is_valid() :
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            pp = form.cleaned_data('photo_profile')
            slug = form.cleaned_data['slug']
            if 'save' in request.POST:
                form.save()
                message = "save"
                return render(request, 'sucesfail/sucess.html')
            else:
                return render(request, 'sucesfail/fail.html')
        else:
            print("form is not valid")
    else:
        print("GET Request")
        return render(request, 'registerlogin/register.html', {'form' : UserRegisterForm()})

def register_view(request) :
    form= UserCreationForm()
    return render


def profile(request) :
    return render (request, 'profile.html')

filum/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Homepage
{% endblock title %}


{% block titleinpage %}
    Home
{% endblock titleinpage %}

{% block content %}
    <p>This is Filum</p>
{% endblock content %}

filum/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
            Filum - {% block title %}   {% endblock title %}
    </title>
    {% comment %} <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="bootstrap/js/bootstrap.bundle.js"></script> {% endcomment %}
    <link rel="stylesheet" href="{%static 'css/style.css' %}">
    <link rel = "icon" href = "{% static 'img/favicon_io/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


</head>
<body>
    <div class="container">
        <nav>
            <a class="disaper" style="margin-bottom: 40px;" href="/">
                <img src=" {% static 'img/favicon_io/favicon.ico' %}" alt="Home">
            </a>
            <a style="margin-top:100px;" href="/">
                <i class="fa-solid fa-house fa-2xl"></i>
            </a>
            <a style="margin-top:80px;" href="/search">
                <i class="fa-solid fa-magnifying-glass fa-2xl"></i>
            </a>
            <a style="margin-top:80px; margin-left:2px;" href="/">
                <i class="fa-regular fa-square-plus fa-2xl"></i>
            </a>
            <a style="margin-top:80px; margin-left:2px;" href="{% url 'user:myprofile' %}">
                <i class="fa-solid fa-user fa-2xl"></i>
            </a>

        </nav>

        <main>
            <div class="titleinpage">
                <h2>
                    {% block titleinpage %}
                    
                    {% endblock titleinpage %}
                </h2>
            </div>
            <div class= "homepost">
                <h1>
                    {% block content %}
                        
                        
                    {% endblock content %}
                </h1>
            </div>
            <div class = "right-sidebar">
                {% block rightsidebar %}
                

                {% endblock rightsidebar %}
            </div>
        </main>
    </div>
</body>
</html>

filum/templates/search.html
{% extends "layout.html" %}

{% block title %}
    Search
{% endblock title %}


{% block titleinpage %}
    Search
{% endblock titleinpage %}

{% block content %}
    This is Search
{% endblock content %}

filum/user/templates/profile.html
{% extends "layout.html" %}
{% load static %}

{% comment %} <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
<script src="bootstrap/js/bootstrap.bundle.js"></script> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">



{% block title %}
    Profile
{% endblock title %}


{% block titleinpage %}
    Profile
{% endblock titleinpage %}

{% block rightsidebar %}
    {% comment %} <button type="button" class="btn btn-dark btn-sm">Register</button> {% endcomment %}
    <button class= "login">Log in</button>

{% endblock rightsidebar %}




{% block content %}
    This is your Profile



{% endblock content %}

filum/user/templates/registerlogin/register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock title %}

{% block titleinpage %}
    Hi New Filumate
{% endblock titleinpage %}

{% block content %}
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
{% endblock content %}